### ISSUE TITLE
utility script: remove an id from jrc_author

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#108]
It would be nice to have a little utility script that lets me remove a particular employee ID from jrc_author. This is occasionally needed. My script doesn't bother prompting the librarian to confirm authors who: (1) have an ORCID on the paper, and (2) have a record in our orcid collection with both an employeeID and an ORCID that matches the one on the paper. I like this; it speeds up curation a lot. Occasionally, though, real, active Janelians will have legitimate reasons for not including Janelia in their affiliations.

Desired usage:
`python3 remove_author.py --doi 10.1038/s41586-024-07558-y --id 50135 --write`
Output might be something like:
```
Employee ID 50135 removed. Remaining Janelia authors:
12345,10987,J4567
```

**Comment by robsv** [comment]
Simple enough to do unless that author is also a first or last author, but I feel that those cases would be pretty rare, and maybe not going down a rabbit hole to code for. Your thoughts?

**Comment by robsv** [comment]
Rather than spending several hours coding for first/last author removal (which will be a rare occurrence), I've added code to detect it and output a message that one or both need to be manually updated. If you'd still like it more automated (without the need for whoever ran the program to notify me that there is a manual update needed to the orcid collection) we can do one of two things:
1) Have the program send me an email
2) Fully automate it - this will take a few hours, as there are lots of edge cases
