### ISSUE TITLE
Get update_tags to use jrc_author?

### ISSUE THREAD

**Issue by virginiascarlett** [JaneliaSciComp/dis-utilities#126]
10.1016/j.isci.2024.111336

John Koberstein is in jrc_author, but update_tags.py recognizes no Janelia authors, and therefore suggests no tags.

**Comment by robsv** [comment]
The issue was that the author's given name ("John N.") wasn't in the database - only "John".
I fixed it by updating the orcid collection, but the proper fix will be one of two things:
1) When adding a Janelia author to a paper, ensure that the author's given/family name is in the orcid collection
2) Somehow override get_author_details to recognize an author without a name or ORCID match (as was the case here) to include entries in jrc_author. This will be ugly, with multiple finds in the orcis collection for a single author.

**Comment by virginiascarlett** [comment]
John Koberstein's name permutations were not added because I was simply neglecting to add name permutations to orcid records in cases where the author doesn't have an ORCID. Now the script does so, assuming the match was approved by the user.
